// The red panda's head as the launcher icon of the simulated phone. Generated by
// web/scripts/mascot-assets.mjs from web/src/components/redPandaShapes.ts — do not edit.
// It takes the props the launcher passes a lucide icon and keeps its own colours.
export function UnibotMark({ size = 48, className, style }: { size?: number | string; color?: string; strokeWidth?: number | string; className?: string; style?: React.CSSProperties }) {
  return (
    <svg viewBox="0 0 48 48" width={size} height={size} className={className} style={style} aria-hidden="true">
      <g transform="translate(-6.49 -5.57) scale(0.3)">
        <path d="M26 52a24 24 0 1 1 48 0a24 24 0 1 1 -48 0z" fill="#bf4f23" />
        <path d="M126 52a24 24 0 1 1 48 0a24 24 0 1 1 -48 0z" fill="#bf4f23" />
        <path d="M30 52a20 20 0 1 1 40 0a20 20 0 1 1 -40 0z" fill="#d8632e" />
        <path d="M130 52a20 20 0 1 1 40 0a20 20 0 1 1 -40 0z" fill="#d8632e" />
        <path d="M37 53a14 14 0 1 1 28 0a14 14 0 1 1 -28 0z" fill="#fff4e6" />
        <path d="M135 53a14 14 0 1 1 28 0a14 14 0 1 1 -28 0z" fill="#fff4e6" />
        <path d="M30 104a70 62 0 1 1 140 0a70 62 0 1 1 -140 0z" fill="#d8632e" />
        <path d="M38 118C38 96 52 84 66 84C82 84 94 98 100 112C106 98 118 84 134 84C148 84 162 96 162 118C162 142.3 134.2 162 100 162C65.8 162 38 142.3 38 118Z" fill="#fff4e6" />
        <path d="M59 108a13 13 0 1 1 26 0a13 13 0 1 1 -26 0z" fill="#2a1a14" />
        <path d="M115 108a13 13 0 1 1 26 0a13 13 0 1 1 -26 0z" fill="#2a1a14" />
        <path d="M72.3 103a4.2 4.2 0 1 1 8.4 0a4.2 4.2 0 1 1 -8.4 0z" fill="#ffffff" />
        <path d="M128.3 103a4.2 4.2 0 1 1 8.4 0a4.2 4.2 0 1 1 -8.4 0z" fill="#ffffff" />
        <path d="M93 128Q100 123 107 128Q104.5 137 100 139Q95.5 137 93 128Z" fill="#2a1a14" />
        <path d="M98.4 138.5h3.2v3.5h-3.2zM91 140.4Q95.5 147.4 100 140.4Q104.5 147.4 109 140.4L109 143.6Q104.5 150.6 100 143.6Q95.5 150.6 91 143.6Z" fill="#2a1a14" />
      </g>
    </svg>
  );
}
