#!/usr/bin/env python3
"""apply-unibot-branding.py — wire Abdullah's final branding into the Android app.

Final brand (locked 2026-10-01):
  * Logo:    the "unibot" wordmark (Uber-style, lowercase, white on black)
  * App icon: the fluffy ninja mascot (violet glowing eyes, katana)

What this does:
  * mipmap-*/ic_launcher_foreground.png — ninja, 108dp adaptive foreground
      (432/324/216/162/108 px for xxxhdpi..mdpi)
  * mipmap-*/ic_launcher.png — ninja legacy icon (192/144/96/72/48)
  * mipmap-*/ic_launcher_classic_dark.png — ninja legacy (same art)
  * mipmap-*/ic_launcher_foreground_u_light.png — black U on white, 108dp
  * mipmap-*/ic_launcher_classic_light.png — black U on white legacy
  * drawable-nodpi/unibot_wordmark.png — the wordmark for in-app use
  * Rewrites the six adaptive-icon XMLs (day/night x main/light/dark):
      main + dark -> ninja foreground on pure black, no monochrome layer
        (a raster mascot can't produce a clean themed-icon silhouette;
         dropping <monochrome> keeps the real icon instead of a broken one)
      light        -> black U on white (forced-light alternate)
  * Launcher backgrounds -> pure black so the ninja blends seamlessly.
  * Deletes the orphaned violet-U vector drawables they replace.

Idempotent: re-running reproduces the same files.
"""

import sys
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
RES = REPO / "android/src/android/app/src/main/res"
BRAND = Path.home() / "workspace/unibot-branding/final"

NINJA = (
    BRAND / "media-generation-unibot-ninja-icon-no-u-0-1d33ce8c-ea4c-4f67-bb93-0535b05b22f4.webp"
)
U_ICON = BRAND / "media-generation-unibot-u-icon-0-66d319b9-0fa1-40cf-94de-46a9613ff764.webp"
WORDMARK = (
    BRAND / "media-generation-unibot-wordmark-final-0-7813cca1-9084-49eb-b7cb-abe3d029ce03.webp"
)

DENSITIES = {  # mipmap dir -> (foreground px @108dp, legacy px)
    "mipmap-xxxhdpi": (432, 192),
    "mipmap-xxhdpi": (324, 144),
    "mipmap-xhdpi": (216, 96),
    "mipmap-hdpi": (162, 72),
    "mipmap-mdpi": (108, 48),
}


def main() -> None:
    for p in (NINJA, U_ICON, WORDMARK):
        if not p.exists():
            sys.exit(f"missing brand asset: {p}")

    ninja = Image.open(NINJA).convert("RGB")
    u_icon = Image.open(U_ICON).convert("RGB")

    # Black U on white: threshold the white-U-on-black icon for a crisp glyph.
    lum = u_icon.convert("L")
    glyph = lum.point(lambda v: 255 if v > 110 else 0)

    for d, (fg_px, leg_px) in DENSITIES.items():
        mdir = RES / d
        mdir.mkdir(parents=True, exist_ok=True)
        ninja.resize((fg_px, fg_px), Image.LANCZOS).save(mdir / "ic_launcher_foreground.png")
        ninja.resize((leg_px, leg_px), Image.LANCZOS).save(mdir / "ic_launcher.png")
        ninja.resize((leg_px, leg_px), Image.LANCZOS).save(mdir / "ic_launcher_classic_dark.png")

        mask = glyph.resize((fg_px, fg_px), Image.LANCZOS)
        light_fg = Image.new("RGB", (fg_px, fg_px), "white")
        light_fg.paste(Image.new("RGB", (fg_px, fg_px), "black"), (0, 0), mask)
        light_fg.save(mdir / "ic_launcher_foreground_u_light.png")
        light_fg.resize((leg_px, leg_px), Image.LANCZOS).save(
            mdir / "ic_launcher_classic_light.png"
        )

    # Wordmark for in-app use (splash / about / settings header).
    nodpi = RES / "drawable-nodpi"
    nodpi.mkdir(parents=True, exist_ok=True)
    Image.open(WORDMARK).convert("RGB").save(nodpi / "unibot_wordmark.png")

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<!-- unibot: final branding 2026-10-01 (ninja mascot / U wordmark).
     Generated by scripts/apply-unibot-branding.py; do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/%(bg)s" />
    <foreground android:drawable="@mipmap/%(fg)s" />
</adaptive-icon>
"""
    variants = {
        # (anydpi xml, night xml, bg color ref, foreground mipmap)
        (
            "mipmap-anydpi-v26/ic_launcher.xml",
            "mipmap-night-anydpi-v26/ic_launcher.xml",
            "ic_launcher_background",
            "ic_launcher_foreground",
        ),
        (
            "mipmap-anydpi-v26/ic_launcher_classic_dark.xml",
            "mipmap-night-anydpi-v26/ic_launcher_classic_dark.xml",
            "ic_launcher_bg_force_dark",
            "ic_launcher_foreground",
        ),
        (
            "mipmap-anydpi-v26/ic_launcher_classic_light.xml",
            "mipmap-night-anydpi-v26/ic_launcher_classic_light.xml",
            "ic_launcher_bg_force_light",
            "ic_launcher_foreground_u_light",
        ),
    }
    for day, night, bg, fg in variants:
        for xml in (day, night):
            (RES / xml).write_text(adaptive % {"bg": bg, "fg": fg})

    # Pure-black launcher backgrounds so the ninja blends seamlessly.
    (RES / "values/ic_launcher_background.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        '    <color name="ic_launcher_background">#FF000000</color>\n</resources>\n'
    )
    (RES / "values-night/ic_launcher_background.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        '    <color name="ic_launcher_background">#FF000000</color>\n</resources>\n'
    )
    alt = RES / "values/ic_launcher_alt_colors.xml"
    alt.write_text(alt.read_text().replace("#0F1B33", "#FF000000"))

    # Remove the violet-U vectors this branding replaces (now unreferenced).
    for vec in (
        "ic_launcher_foreground_ub.xml",
        "ic_launcher_foreground_ub_dark.xml",
        "ic_launcher_monochrome.xml",
    ):
        p = RES / "drawable" / vec
        if p.exists():
            p.unlink()
            print("removed", p.relative_to(REPO))

    # Safety: fail loudly if live code/resources still reference the deleted vectors
    # (scripts/ are historical generator records and may mention them).
    import subprocess

    refs = subprocess.run(
        ["grep", "-rn", "ic_launcher_foreground_ub\\|ic_launcher_monochrome", "android/src"],
        capture_output=True,
        text=True,
        cwd=REPO,
    ).stdout.strip()
    if refs:
        sys.exit("still referenced:\n" + refs)

    print("branding applied OK")


if __name__ == "__main__":
    main()
