#!/usr/bin/env python3
"""Generate the unibot launcher and status-bar icons for android/ from assets/brand/.

Idempotent; re-run after every upstream pull (CONTRIBUTING.md). Writes:

- drawable/ic_launcher_foreground_nm.xml       the one-stroke N, gradient fill, 108dp canvas
- drawable/ic_launcher_foreground_nm_dark.xml  the same path, white (the "Dark" icon skin)
- drawable/ic_launcher_monochrome.xml          the same path, flat (Android 13+ themed icons)
- drawable/ic_stat_unibot.xml                24dp flat mark for notification small icons
- mipmap-anydpi-v26/ic_launcher*.xml           the three adaptive icons (auto / light / dark)
- values*/ic_launcher_background.xml, values/ic_launcher_alt_colors.xml  tile colours
- mipmap-*/ic_launcher*.png                    legacy rasters, when Playwright is installed

Geometry: the mark's tile is 0..100 units == the 72dp visible area of a 108dp adaptive
icon, so x' = 18 + 0.72 * x. The farthest point of the mark from the centre is ~29dp,
inside the 33dp circle that themed icons and round masks keep.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / "assets" / "brand"
RES = ROOT / "android" / "src" / "android" / "app" / "src" / "main" / "res"

STROKE_START = "#015CFB"
STROKE_END = "#0186FB"
TILE_LIGHT = "#FFFFFF"
TILE_DARK = "#0F1B33"
SCALE, OFFSET = 0.72, 18.0
TOKEN = re.compile(r"[MLCZ]|-?\d*\.?\d+")


def mark_path() -> str:
    svg = (BRAND / "unibot-mark.svg").read_text(encoding="utf-8")
    match = re.search(r'<path[^>]*\sd="([^"]+)"', svg)
    if not match:
        sys.exit("assets/brand/unibot-mark.svg: no <path d=...>")
    return match.group(1)


def transform(d: str, scale: float, ox: float, oy: float | None = None) -> str:
    """Absolute M/L/C/Z path data, scaled and translated, 2 decimals."""
    if oy is None:
        oy = ox
    text = ""
    n = 0
    for tok in TOKEN.findall(d):
        if tok in "MLCZ":
            text += tok
        else:
            offset = ox if n % 2 == 0 else oy
            text += f"{offset + scale * float(tok):.2f} "
            n += 1
    return re.sub(r" (?=[MLCZ])", "", text).strip()


def path_bbox(d: str) -> tuple[float, float, float, float]:
    nums = [float(t) for t in TOKEN.findall(d) if t not in "MLCZ"]
    xs, ys = nums[0::2], nums[1::2]
    return min(xs), min(ys), max(xs), max(ys)


def vector(path: str, fill: str, size: int, viewport: int, comment: str) -> str:
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- unibot: {comment} Generated by scripts/gen-android-icons.py from
     assets/brand/unibot-mark.svg; do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="{size}dp" android:height="{size}dp"
    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">
    <path android:pathData="{path}"{fill}
</vector>
"""


def gradient_fill(x0: float, x1: float, y: float) -> str:
    return f""">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear"
                android:startX="{x0:.2f}" android:startY="{y:.0f}"
                android:endX="{x1:.2f}" android:endY="{y:.0f}"
                android:startColor="#FF{STROKE_START[1:]}" android:endColor="#FF{STROKE_END[1:]}" />
        </aapt:attr>
    </path>"""


def flat_fill(argb: str) -> str:
    return f' android:fillColor="{argb}" />'


def adaptive(background: str, foreground: str) -> str:
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- unibot: generated by scripts/gen-android-icons.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="{background}" />
    <foreground android:drawable="{foreground}" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")
        print(f"  wrote {path.relative_to(ROOT)}")


def set_color(path: Path, name: str, value: str) -> None:
    text = path.read_text(encoding="utf-8")
    new = re.sub(rf'(<color name="{name}">)#[0-9A-Fa-f]+(</color>)', rf"\g<1>{value}\g<2>", text)
    if new != text:
        path.write_text(new, encoding="utf-8")
        print(f"  {path.relative_to(ROOT)}: {name} = {value}")


def vectors(d: str) -> None:
    p108 = transform(d, SCALE, OFFSET)
    x0, _, x1, _ = path_bbox(p108)
    drawable = RES / "drawable"
    write(
        drawable / "ic_launcher_foreground_nm.xml",
        vector(
            p108,
            gradient_fill(x0, x1, 54),
            108,
            108,
            "launcher foreground, the N in the brand gradient.",
        ),
    )
    write(
        drawable / "ic_launcher_foreground_nm_dark.xml",
        vector(
            p108, flat_fill("#FFFFFFFF"), 108, 108, "launcher foreground for the Dark icon skin."
        ),
    )
    write(
        drawable / "ic_launcher_monochrome.xml",
        vector(
            p108,
            flat_fill("#FFFFFFFF"),
            108,
            108,
            "themed-icon silhouette; the system re-tints it.",
        ),
    )
    # 24dp status-bar icon: the mark in a 20dp box centred on the 24dp canvas.
    bx0, by0, bx1, by1 = path_bbox(d)
    scale = 20 / max(bx1 - bx0, by1 - by0)
    p24 = transform(d, scale, 12 - scale * (bx0 + bx1) / 2, 12 - scale * (by0 + by1) / 2)
    write(
        drawable / "ic_stat_unibot.xml",
        vector(p24, flat_fill("#FFFFFFFF"), 24, 24, "notification small icon (alpha mask)."),
    )
    anydpi = RES / "mipmap-anydpi-v26"
    write(
        anydpi / "ic_launcher.xml",
        adaptive("@color/ic_launcher_background", "@drawable/ic_launcher_foreground_nm"),
    )
    write(
        anydpi / "ic_launcher_classic_light.xml",
        adaptive("@color/ic_launcher_bg_force_light", "@drawable/ic_launcher_foreground_nm"),
    )
    write(
        anydpi / "ic_launcher_classic_dark.xml",
        adaptive("@color/ic_launcher_bg_force_dark", "@drawable/ic_launcher_foreground_nm_dark"),
    )
    set_color(RES / "values" / "ic_launcher_background.xml", "ic_launcher_background", TILE_LIGHT)
    set_color(
        RES / "values-night" / "ic_launcher_background.xml", "ic_launcher_background", TILE_LIGHT
    )
    set_color(
        RES / "values" / "ic_launcher_alt_colors.xml", "ic_launcher_bg_force_light", TILE_LIGHT
    )
    set_color(RES / "values" / "ic_launcher_alt_colors.xml", "ic_launcher_bg_force_dark", TILE_DARK)


def rasters(d: str) -> None:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("  playwright not installed: legacy PNG icons left as they are")
        return
    densities = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
    grad = (
        f'<linearGradient id="g" gradientUnits="userSpaceOnUse" x1="12.6" y1="50" x2="87.8" y2="50">'
        f'<stop offset="0" stop-color="{STROKE_START}"/><stop offset="1" stop-color="{STROKE_END}"/></linearGradient>'
    )
    tile = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs>{grad}</defs>'
        f'<rect width="100" height="100" rx="27" ry="27" fill="{TILE_LIGHT}"/><path d="{d}" fill="url(#g)"/></svg>'
    )
    p108 = transform(d, SCALE, OFFSET)
    x0, _, x1, _ = path_bbox(p108)
    grad_108 = (
        f'<linearGradient id="g" gradientUnits="userSpaceOnUse" x1="{x0:.2f}" y1="54" x2="{x1:.2f}" y2="54">'
        f'<stop offset="0" stop-color="{STROKE_START}"/><stop offset="1" stop-color="{STROKE_END}"/></linearGradient>'
    )

    def foreground(fill: str) -> str:
        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108"><defs>{grad_108}</defs>'
            f'<path d="{p108}" fill="{fill}"/></svg>'
        )

    jobs: list[tuple[Path, str, int]] = []
    for name, k in densities.items():
        for prefix in ("mipmap", "mipmap-night"):
            folder = RES / f"{prefix}-{name}"
            if not folder.is_dir():
                continue
            if (folder / "ic_launcher.png").exists():
                jobs.append((folder / "ic_launcher.png", tile, round(48 * k)))
            for fg_name, fill in (
                ("ic_launcher_foreground.png", "url(#g)"),
                ("ic_launcher_foreground_light.png", "url(#g)"),
                ("ic_launcher_foreground_dark.png", "#FFFFFF"),
            ):
                if (folder / fg_name).exists():
                    jobs.append((folder / fg_name, foreground(fill), round(108 * k)))
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        for target, svg, px in jobs:
            page.set_viewport_size({"width": px, "height": px})
            page.set_content(f'<body style="margin:0;background:transparent">{svg}</body>')
            page.locator("svg").evaluate(
                "(e, s) => { e.setAttribute('width', s); e.setAttribute('height', s); }", str(px)
            )
            page.screenshot(
                path=str(target),
                omit_background=True,
                clip={"x": 0, "y": 0, "width": px, "height": px},
            )
        browser.close()
    print(f"  {len(jobs)} legacy PNGs rendered")


def main() -> None:
    d = mark_path()
    print("== launcher icons")
    vectors(d)
    rasters(d)


if __name__ == "__main__":
    main()
