#!/usr/bin/env python3
"""Generate the unibot launcher and status-bar icons. Idempotent.

Writes:
- drawable/ic_launcher_foreground_ub.xml       the U mark, violet gradient, 108dp
- drawable/ic_launcher_foreground_ub_dark.xml  the U mark, white (dark tile)
- drawable/ic_launcher_monochrome.xml          the U mark, flat white (themed icons)
- drawable/ic_stat_unibot.xml                  24dp flat mark for notification small icons
- mipmap-anydpi-v26/ic_launcher*.xml           adaptive icons -> the new foregrounds
- mipmap-night-anydpi-v26/ic_launcher*.xml     night adaptive icons (dark tile, white mark)
- values-night/ic_launcher_background.xml      dark tile colour

Deletes the legacy raster mipmaps (mipmap-{mdpi,hdpi,xhdpi,xxhdpi,xxxhdpi} and
their night variants): minSdk is 26, so mipmap-anydpi-v26 always resolves and
the old unibot PNGs must not ship.

Geometry: the mark's tile is 0..100 units == the 72dp visible area of a 108dp
adaptive icon, so x' = 18 + 0.72 * x.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "android" / "src" / "android" / "app" / "src" / "main" / "res"

# The unibot "U", drawn in a 0..100 tile.
U_100 = "M28,18 L28,52 Q28,74 50,74 Q72,74 72,52 L72,18 L58,18 L58,52 Q58,60 50,60 Q42,60 42,52 L42,18 Z"

VIOLET_START = "#FF6D28D9"
VIOLET_END = "#FF8B5CF6"
WHITE = "#FFFFFFFF"
NIGHT_TILE = "#FF1C1C1E"


def scale_path(d: str, scale: float, offset: float = 0.0) -> str:
    return re.sub(r"\d+(?:\.\d+)?", lambda m: f"{offset + scale * float(m.group(0)):.2f}", d)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)}")


def foreground_108(path_d: str, fill: str, comment: str) -> str:
    if fill == "gradient":
        fill_block = (
            '        <aapt:attr name="android:fillColor">\n'
            '            <gradient android:type="linear"\n'
            '                android:startX="38.16" android:startY="54"\n'
            '                android:endX="69.84" android:endY="54"\n'
            f'                android:startColor="{VIOLET_START}" android:endColor="{VIOLET_END}" />\n'
            "        </aapt:attr>"
        )
    else:
        fill_block = ""
        path_attr = f' android:fillColor="{fill}"'
    if fill == "gradient":
        path_el = f'    <path android:pathData="{path_d}">\n{fill_block}\n    </path>'
    else:
        path_el = f'    <path android:pathData="{path_d}"{path_attr} />'
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"<!-- unibot: {comment} Generated by scripts/gen-unibot-icons.py; do not edit by hand. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="108" android:viewportHeight="108">\n'
        f"{path_el}\n"
        "</vector>\n"
    )


def main() -> None:
    d108 = scale_path(U_100, 0.72, 18.0)
    d24 = scale_path(U_100, 0.24, 0.0)

    write(
        RES / "drawable" / "ic_launcher_foreground_ub.xml",
        foreground_108(d108, "gradient", "launcher foreground, the U in the brand gradient."),
    )
    write(
        RES / "drawable" / "ic_launcher_foreground_ub_dark.xml",
        foreground_108(d108, WHITE, "launcher foreground, white U for the dark tile."),
    )
    write(
        RES / "drawable" / "ic_launcher_monochrome.xml",
        foreground_108(d108, WHITE, "themed-icon silhouette; the system re-tints it."),
    )
    write(
        RES / "drawable" / "ic_stat_unibot.xml",
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- unibot: notification small icon (alpha mask). Generated by scripts/gen-unibot-icons.py. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp" android:height="24dp"\n'
        '    android:viewportWidth="24" android:viewportHeight="24">\n'
        f'    <path android:pathData="{d24}" android:fillColor="{WHITE}" />\n'
        "</vector>\n",
    )

    # stale unibot-generated vectors
    for stale in [
        "ic_launcher_foreground_nm.xml",
        "ic_launcher_foreground_nm_dark.xml",
        "ic_stat_unibot.xml",
    ]:
        p = RES / "drawable" / stale
        if p.exists():
            p.unlink()
            print(f"  deleted {p.relative_to(ROOT)}")

    # legacy rasters: anydpi-v26 wins on every supported device (minSdk 26)
    for d in list(RES.glob("mipmap-*")):
        if d.name not in ("mipmap-anydpi-v26", "mipmap-night-anydpi-v26"):
            shutil.rmtree(d)
            print(f"  deleted {d.relative_to(ROOT)}/")

    day = RES / "mipmap-anydpi-v26"
    night = RES / "mipmap-night-anydpi-v26"
    for name in ["ic_launcher.xml", "ic_launcher_classic_light.xml"]:
        p = day / name
        if p.exists():
            t = p.read_text(encoding="utf-8")
            t = t.replace(
                "@drawable/ic_launcher_foreground_nm", "@drawable/ic_launcher_foreground_ub"
            )
            t = t.replace(
                "unibot: generated by scripts/gen-android-icons.py.",
                "unibot: generated by scripts/gen-unibot-icons.py.",
            )
            p.write_text(t, encoding="utf-8")
            print(f"  edited {p.relative_to(ROOT)}")
    p = day / "ic_launcher_classic_dark.xml"
    if p.exists():
        t = p.read_text(encoding="utf-8")
        t = t.replace(
            "@drawable/ic_launcher_foreground_nm", "@drawable/ic_launcher_foreground_ub_dark"
        )
        t = t.replace(
            "unibot: generated by scripts/gen-android-icons.py.",
            "unibot: generated by scripts/gen-unibot-icons.py.",
        )
        p.write_text(t, encoding="utf-8")
        print(f"  edited {p.relative_to(ROOT)}")

    # night: dark tile + white mark; stop referencing the deleted PNG foregrounds
    for name in [
        "ic_launcher.xml",
        "ic_launcher_classic_dark.xml",
        "ic_launcher_classic_light.xml",
    ]:
        p = night / name
        if not p.exists():
            continue
        t = p.read_text(encoding="utf-8")
        t = re.sub(
            r"<foreground>.*?</foreground>",
            '        <foreground android:drawable="@drawable/ic_launcher_foreground_ub_dark" />',
            t,
            flags=re.S,
        )
        t = t.replace(
            "@mipmap/ic_launcher_foreground_dark", "@drawable/ic_launcher_foreground_ub_dark"
        )
        t = t.replace(
            "@mipmap/ic_launcher_foreground_light", "@drawable/ic_launcher_foreground_ub_dark"
        )
        t = t.replace(
            '@mipmap/ic_launcher_foreground"', '@drawable/ic_launcher_foreground_ub_dark"'
        )
        t = t.replace(
            "unibot: generated by scripts/gen-android-icons.py.",
            "unibot: generated by scripts/gen-unibot-icons.py.",
        )
        p.write_text(t, encoding="utf-8")
        print(f"  edited {p.relative_to(ROOT)}")
    write(
        RES / "values-night" / "ic_launcher_background.xml",
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<resources>\n"
        f'    <color name="ic_launcher_background">{NIGHT_TILE}</color>\n'
        "</resources>\n",
    )

    # Kotlin reference to the old status icon
    kt = (
        ROOT
        / "android"
        / "src"
        / "android"
        / "app"
        / "src"
        / "main"
        / "java"
        / "ai"
        / "unicto"
        / "unibot"
        / "ui"
        / "cloud"
        / "CloudSignInScreen.kt"
    )
    if kt.is_file():
        t = kt.read_text(encoding="utf-8")
        if "ic_stat_unibot" in t:
            kt.write_text(t.replace("ic_stat_unibot", "ic_stat_unibot"), encoding="utf-8")
            print(f"  edited {kt.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
