#!/usr/bin/env python3
"""Historical record: how nanoMuse became unibot (2026-10-01).

This is NOT a runnable rebrand script — it is the record of the one-time
rebrand performed when forking nano-muse/nanoMuse into unictoai/unibot.
Do not run it; the work is done. It exists so a future maintainer can see
exactly what changed and why, especially the decisions that differ from
upstream's own rebrand script (scripts/rebrand.py, now an obsolete stub).

Product decisions (2026-10-01):
- Name: unibot (lowercase), violet palette (#6D28D9 / #8B5CF6 / #A78BFA)
- GitHub: unictoai/unibot | Android: ai.unicto.unibot | version 0.1.0 (code 1)
- Bring-your-own-key first: unibot operates NO relay, NO sign-in service,
  NO funded allowance. The relay in cloud/ is self-hosted software only.
- Attribution preserved: fork of nanoMuse (GPL-3.0-or-later), which stands
  on OpenMinis. See NOTICE.

What was changed (mechanical passes + hand fixes):
1. Gradle: namespace/applicationId ai.unicto.unibot, versionCode 1,
   versionName 0.1.0, signing config renamed to "unibot".
2. Kotlin/Java: com.openminis.app -> ai.unicto.unibot,
   io.github.nanomuse.* -> ai.unicto.unibot.* (packages moved on disk).
   MinisAccessibilityService -> UnibotAccessibilityService.
   ServiceLoader: ai.unicto.unibot.crash.CrashFileSenderFactory.
   DocumentsProvider authority: ai.unicto.unibot.minis.documents.
   Rclone gomobile Java package: ai.unicto.unibot.rclone.
3. Android resources: nm_ prefix -> ub_ (~3,200 occurrences, 65 files);
   nm_strings.xml -> ub_strings.xml; backup rules renamed to
   unibot_backup_rules.xml / unibot_data_extraction_rules.xml.
   New violet launcher + notification icons generated by
   scripts/gen-unibot-icons.py (ic_launcher_foreground_ub*.xml,
   ic_launcher_monochrome.xml, ic_stat_unibot.xml); stale nanoMuse
   vectors and raster mipmaps removed.
4. Internal minis:// protocol KEPT deliberately (105 files of rootfs
   plumbing; renaming it buys nothing and risks breakage).
5. Native commands renamed: nanomuse-media/-hands/-pc -> unibot-media/-hands/-pc
   (audit runtime scripts/prompts before changing again).
6. Python (unibot/): imports -> unibot; version 0.1.0; CloudSettings
   base_url default "" and required False (no hosted relay).
7. Web (web/): rebuilt bundles; own-key docs link -> GitHub;
   community notice -> GitHub; invite fallback empty without relay URL.
8. Relay (cloud/): INVITE_URL default "", OWN_KEY_DOCS default -> GitHub
   docs/own-key.md; e-mail footer de-branded (no domain); .env.example
   uses your-relay.example placeholders.
9. Desktop (desktop/): app id ai.unicto.unibot.desktop; nanomuse_desktop/
   -> unibot_desktop/; DEFAULT_CLOUD ""; packaging homepage -> GitHub.
10. iOS (android/src/ios/): NanoMuse* files -> Unibot*; bundle ids
    ai.unicto.unibot.*; defaultBase "" (no hosted relay).
11. CI/workflows: ghcr.io/nano-muse -> ghcr.io/unictoai; release APK
    unibot-<version>-arm64.apk on v* tags.
12. Headers: X-Nanomuse-Bridge/Code -> X-Unibot-Bridge/Code.
13. Docs: README rewritten (BYOK, no-account); privacy.md + own-key.md +
    cloud.md reframed around "no unibot-operated services"; release-notes
    template de-branded; translated READMEs stubbed to English.
14. site/ (their unibot.cn web site) and .github/workflows/pages.yml
    REMOVED — the fork operates no site; keeping it would redirect our
    users to infrastructure we do not control.
15. All version sources aligned to 0.1.0 (Android, Python, web, desktop, iOS).

Deliberately NOT changed:
- minis:// URIs, MinisApp/MinisSkills internal identifiers (compat).
- OpenMinis attribution in NOTICE/About ("Based on OpenMinis 1.13").
- docs/releases/v0.1.*.md historical notes (upstream history).
- demo/showcase + cloud/deploy: their ops configs, inert unless installed.
- proot submodule (nano-muse/proot), still fetched from upstream.

Verification done 2026-10-01: repo-wide grep for nanomuse/nano-muse/
nanomuse.cn/unibot.cn/com.openminis/io.github.nanomuse/io.github.unibot
clean except intentional attributions + history; AndroidManifest +
string XMLs parse; no dangling nm_ resource references. NOT yet compiled
(no Android SDK locally) — first compile happens in GitHub Actions after
the fork exists at unictoai/unibot.
"""
